yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Название группы'
    )
    slug = models.SlugField('Адрес', unique=True, help_text='Адрес группы')
    description = models.TextField(
        'Описание', help_text='Описание группы')

    class Meta:
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст', help_text='Текст поста')
    pub_date = models.DateTimeField('Дата пуликации',
                                    help_text='Дата публикации поста',
                                    auto_now_add=True,)
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Связанная группа'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return (self.text[:15])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               null=True)
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (f'Комментарий {self.author.username} к посту {self.post.id}')

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=('post', 'author'), name='unique_object')]


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=('user', 'author'), name='unique_object')]

    def __str__(self) -> str:
        return (f'Подписка {self.user.username}'
                f' на автора {self.author.username}')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(),
        }
        labels = {
            'text': 'Текст'
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required


from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

from yatube.settings import POSTS_QUANTITY


def paginate(request, queryset):
    paginator = Paginator(queryset, POSTS_QUANTITY)
    page_number = request.GET.get
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.all()
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginate(request, posts)
    try:
        following = Follow.objects.get(user=request.user, author=author)
    except Exception:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'post_id': post_id,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, POSTS_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author_follow = get_object_or_404(User, username=username)
    if author_follow != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author_follow)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follow = Follow.objects.filter(
        author__username=username, user=request.user)
    follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}Редактировать пост
{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body" >
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
        {% endif %}
        <form method="post" enctype="multipart/form-data"
          {% if is_edit %}
          action='{% url 'posts:post_edit' post_id %}'
          {% else %}
          action='{% url 'posts:post_create' %}'
          {% endif %}>
            {% csrf_token %}
            {% for field in form %}
          <div class="form-group row my-3"
            {% if field.field.required %}
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">
            {% if is_edit %}
              Сохранить
            {% else %}
              Добавить
            {% endif %}
          </button>
          </div>
        </form>
      </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title%}
Подписки
{% endblock title %}
{% block content %}
<div class="container">
  <h1> Публикации избранных авторов </h1>
  {% include 'posts/includes/menu.html' %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}"> все посты пользователя </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a></p>
    {% if post.group.slug %}
      <p><a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a></p>
    {% endif %}
  </article>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Страница группы {{ group.title }}
{% endblock %}
{% block content %} 
  <div class="container py-5"> 
    <h1>{{ group }}</h1> 
    <p> 
      {{ group.description|linebreaksbr }} 
    </p> 
    {% for post in page_obj %} 
      <article> 
        {% include 'posts/includes/post.html' %} 
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
      </article> 
      <hr>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% load cache  %}
    {% cache 20 index_page %}
      {% include 'posts/includes/menu.html' %}
        {% for post in page_obj %}
          {% load thumbnail %}
          <div class="container">
          {% if forloop.first %}
            <h1> Последние обновления на сайте </h1>
          {% endif %}
            <article> 
              {% include 'posts/includes/post.html' %}
              <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
              <br>
              {% if post.group %}
              <a href="{% url 'posts:group' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
              {% endif %}
            </article>
              {% if not forloop.last %}
                <hr>
              {% endif %}
          </div>
         {% endfor %}
      {% endcache %}
  {% include 'posts/includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group' post.group.slug %}">
              {{ post.group.title }}
            </a>
          </li>
        {% endif %}

        <li class="list-group-item">
          {% include 'posts/includes/author_page.html'%}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Число постов автора:  <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if user == post.author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        Редактировать запись
      </a>
      {% endif %}
    </article>
  </div>
</div>
{% load user_filters %}
{% include 'posts/includes/comment.html' with post=post items=post.comments.all form=form author=username %}

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  Все посты пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>   
      {% for post in page_obj %}
      <article> 
        <ul>
          <li>
            {% include 'posts/includes/author_page.html'%}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
      </article> 
      {% if post.group %} 
        <a href="{% url 'posts:group' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}